telegram:
  token: "7978393304:AAGLZbcn2B_Y7uKhO1Xq42SYRww8xshxUTE"

redis:
  address: "localhost:6379"
  password: ""
  db: 0

data_base:
  connection: "postgres://admin:secret@localhost:5432/telegram_informer?sslmode=disable"

nats:
  url: "nats://nats:4222"
  jet_stream: true