telegram:
  token: "7978393304:AAFFdtGlUwlzIx1zRFv4t7r-HkgH4UpWcMA"
redis:
  address: "localhost:6379"
  password: ""
  db: 0
db:
  connection: "postgres://admin:secret@localhost:5432/telegram_informer?sslmode=disable"
